### ISSUE TITLE
Do you need to depend on lodash.noop & lodash.reduce?

### ISSUE THREAD

**Issue by rpearce** [wimpyprogrammer/react-responsive-breakpoints#86]
Hi, cool library! There are some dependencies I noticed that perhaps don't need to be here?
  * `lodash.noop`:  `Function.prototype` should be a perfectly good stand-in for a no-op, meaning there shouldn't be a need for a third party? Unless, of course, I'm missing something
  * `lodash.reduce`: `options.breakpoints.reduce()` should suffice for a `reduce` function instead of needing to rely on another dependency?

Best,
Robert

**Comment by wimpyprogrammer** [comment]
Hi Robert, thanks for the feedback!  You're totally right.  I used to use lodash functions liberally for cross-browser consistency or to eliminate boilerplate utilities in my own code.  But more recently I've seen the bloat that those dependencies add and try to avoid that.

In #87 I've made simple substitutions for `lodash.noop` and `lodash.reduce`, and made a local copy of `lodash.throttle` that removes features that I'm not using.

Thanks again for the suggestions!

**Comment by wimpyprogrammer** [comment]
I included this change in [version 2.1.0](https://github.com/wimpyprogrammer/react-responsive-breakpoints/releases/tag/2.1.0) and the new package size is much better.

I ran [`package-size`](https://www.npmjs.com/package/package-size) to calculate the bundle sizes.

| Version | Size | Minified | Gzipped |
|---|---|---|---|
| 2.0.0 | 88.34 KB | 16.52 KB | 5.87 KB |
| 2.1.0 | 12.19 KB | 4.27 KB | 1.44 KB |

**Comment by rpearce** [comment]
That's great. And if you want to reduce `throttle` to even more barebones (depending on how you use it`, check this out; it might be all you need?
https://github.com/rpearce/react-popover-a11y/blob/master/source/throttle.js

And tests:
https://github.com/rpearce/react-popover-a11y/blob/master/test/throttle.test.js

I bring this stuff up because package size is a big deal, and I thought this stuff could help! It seems it has a bit already. Thanks for looking at it
